### PR TITLE
Periphery vvet renaming

### PR DESCRIPTION
**Pull request by xenide**
1. Regarding the VVET contract in contracts/test
- I know we're probably not going to be using this version in the end as the new vvet is coming out soon, but it's still good to document some things. 
- Adapted it from a byte ahead's `VVET9.sol`. Enabled (uncommented) the fallback receive function. Upgraded the solidity version to 0.6.6
- The IVVET interface is exactly the same as the IWETH interface

2. Did not change ETH references for VexchangeV1 related code, since the interface was written that way. So in files that use the v1 interface, like `ExampleFlashSwap.sol`, some references to ETH are intact.

3. Also renamed the ETH references to VET in the TransferHelper class

4. All tests are passing, except for those that involve gas cost. The expected gas values in 5 test cases are off by a few gas. In the original code I noticed that the uniswap devs commented that the gas tests are inconsistent. We can either:
- modify the expected gas value 
- remove the gas test altogether 

I think the first choice of modifying the expected gas value makes more sense. In case there are any unexpected changes that break it in the future. Any thoughts?

### CODE REVIEW

**Comment by OliverNChalk** [comment]
Just went through it, looks good but can we point it at `dev` for now so that the auditors don't get extra noise. Once pointed at `dev` I'm happy for this to be merged

**Comment by xenide** [comment]
alright changed the target branch to `dev` instead of `main`.

thanks

**Review by OliverNChalk — APPROVED** [review]

**Review by leodsoft — APPROVED** [review]
Looks good.

For the gas costs, yes I think its best to keep them and adjust as needed; this is the approach I took in the core as well.

For the case where the gas costs are not 100% consistent, I don't have a complete understanding yet but I believe when that occurs it will be one of 2 or possibly 3 variations - and is caused by the EVM implementation.

I found an existing implementation of uniswap's that just reruns tests to accomodate it - and in some of my additions you'll notice where I have allowed a few tests cases to verify with one of several values.

**Comment by xenide** [comment]
In the last commit, we have the code to handle the:
1. New expected gas values
2. When it could be one of two values (either-or case, not deterministic)

If there are no objections I'll proceed to merge into `dev`

**Review by leodsoft — APPROVED** [review]

**Comment by leodsoft** [comment]
all good

**Pull request merged**
